services:
  - type: web
    name: dispatch-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_SECRET_KEY
        value: 你剛剛產生的密鑰

